### ISSUE TITLE
 Фидбек по конкурсной работе от проверяющих

### ISSUE THREAD

**Issue by b1ng0o** [roman-struchev/tinkoff-invest#2]
Необходима дальнейшая разработка. 

Что необходимо:

- сделать параметризацию и запуск/остановку работы стратегий в рантайме
- инвестировать время в обработку возможных ошибок
- продумать визуализацию хода работы + ошибок
- Readme хороший, а документация кода минимальна.

По качеству кода чувствуется сырость и спешка, но несмотря на это работа очень сильная.

**Comment by b1ng0o** [comment]
Мы  рады будем продолжению развития проекта и  получать информацию об обновлениях в наших Телеграмм чатах) или может быть есть аккаунт в Пульсе где ведете статистику или рассказываете о роботе)

**Comment by roman-struchev** [comment]
@b1ng0o, спасибо за отзыв и варианты улучшений!

Буду планировать определенные доработки, кроме работы над визуализацией и управлением стратегиями в рантайме, в первую очередь планирую поддержать новые типы стратегий, т.к. существующий тип по арбитражу валюты стал убыточным из-за увеличения комиссий по валютным инструментам.
